### ISSUE TITLE
No module named 'ChemSpaceAL.SamplingForDocking'

### ISSUE THREAD

**Issue by shijiale0609** [gregory-kyro/ChemSpaceAL#1]
I tried to run the given colab notebook but met the following problems. Could you help fix them?
<img width="716" alt="Screenshot 2024-02-17 at 10 26 30 AM" src="https://github.com/gregory-kyro/ChemSpaceAL/assets/22111378/43d7e0ac-76cb-4f2b-8e48-f5a99209e0d2">

Furthermore, many paths in that notebook are local path, like , not colab path. It seems that the colab notebook was uploaded from the local environment and has not been tested on the colab.

''''''
extract_top_10_smiles('C:/Users/Gregory/Desktop/ChemSpaceAL/files/scored_al5.csv',
                      'C:/Users/Gregory/Desktop/ChemSpaceAL/files/top10_scored_al5.csv')
''''''

**Comment by gregory-kyro** [comment]
Hi Jiale,

Please find our up-to-date GitHub repository for ChemSpaceAL here: https://github.com/batistagroup/ChemSpaceAL

There, you can find the updated tutorial notebook: https://github.com/batistagroup/ChemSpaceAL/blob/main/ChemSpaceAL.ipynb

Please let me know if you have any more questions. I hope this helps.

Best,
Gregory
