### ISSUE TITLE
small fix suggestion

### ISSUE THREAD

**Issue by orgw** [gregory-kyro/ChemSpaceAL#2]
Hi thanks for code!

I suggest to Use round() instead of int() in ALConstruction:

cluster_to_n = {k: int(v * n_samples) for k, v in probabilities.items()}
to
cluster_to_n = {k: round(v * n_samples) for k, v in probabilities.items()}

Using round() will more accurately distribute samples based on the proportion, especially when the total sample size is small.

int() seems to return 0 when sample size is too small.

**Comment by orgw** [comment]
one more, in Dataset


        cur_iter = f"al{config.al_iteration}"
        prev_iter = f"al{config.al_iteration - 1}"
        if config.al_iteration != 0:
            al_path = al_path.replace(cur_iter, prev_iter)
            
            maybe adding this helps? if cur_iter is 0, it becomes -1..

**Comment by gregory-kyro** [comment]
Thank you for the comments! We will consider integrating these suggestions.

FYI: you can find the updated ChemSpaceAL software here: https://github.com/batistagroup/ChemSpaceAL

Best,
Gregory
